site_name: 5pils
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: 5pils
      handlers:
        python:
          options:
            docstring_style: numpy